;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Terroria/AbilitySystem/GameplayTags/DT_MessageTags.DT_MessageTags
+GameplayTagTableList=/Game/Terroria/AbilitySystem/GameplayTags/DT_CommonTags.DT_CommonTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.Montage.PrimaryAttack",DevComment="Montage Event tag : Primary Attack")

