;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Terroria/AbilitySystem/GameplayTags/DT_MessageTags.DT_MessageTags
+GameplayTagTableList=/Game/Terroria/AbilitySystem/GameplayTags/DT_CommonTags.DT_CommonTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Event.Upgrade.F",NewTagName="Event.Upgrade.Flash")
+GameplayTagList=(Tag="Event.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Ranged",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Open",DevComment="")
+GameplayTagList=(Tag="Event.Montage.BlackHole",DevComment="")
+GameplayTagList=(Tag="Event.Montage.DarkShield",DevComment="")
+GameplayTagList=(Tag="Event.Montage.LightingBolt",DevComment="")
+GameplayTagList=(Tag="Event.Montage.PrimaryAttack",DevComment="Montage Event tag : Primary Attack")
+GameplayTagList=(Tag="Event.Montage.ShockWave",DevComment="")
+GameplayTagList=(Tag="Event.Socket.Weapon01",DevComment="")
+GameplayTagList=(Tag="Event.Socket.Weapon02",DevComment="")
+GameplayTagList=(Tag="Event.Socket.Weapon03",DevComment="")
+GameplayTagList=(Tag="Event.Socket.Weapon04",DevComment="")
+GameplayTagList=(Tag="Event.Socket.Weapon05",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.Agility",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.CDR",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.CriticalHitChance",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.CriticalHitDamage",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.E",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.Flash",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.HealthRegen",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.Intelligence",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.Luck",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.ManaRegen",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.MaxMana",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.MovementSpeed",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.Q",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.R",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.Strength",DevComment="")
+GameplayTagList=(Tag="Event.Upgrade.W",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.Flash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.Shield",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Ability.ShockWave",DevComment="")
+GameplayTagList=(Tag="GameplayCue.UI.Damage",DevComment="")
+GameplayTagList=(Tag="Shop.Category.Ability",DevComment="")
+GameplayTagList=(Tag="Shop.Category.Attribute",DevComment="")
+GameplayTagList=(Tag="State.Cancelable",DevComment="")

